# config/cloudinary.yml
development:
  cloud_name: demjitubh
  api_key: '732883849978183'
  api_secret: 47zBCI426NQ9IhPIiIC6qS610rA
  enhance_image_tag: true
  static_image_support: false

production:
  cloud_name: demjitubh
  api_key: '732883849978183'
  api_secret: 47zBCI426NQ9IhPIiIC6qS610rA
  enhance_image_tag: true
  static_image_support: false
